package test

import (
	"archive/zip"
	"bytes"
	"encoding/binary"
	"encoding/json"
	"flag"
	"io"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/okamumu/gospn/pkg/analysis"
	"github.com/okamumu/gospn/pkg/jsonout"
	"github.com/okamumu/gospn/pkg/matout"
	"github.com/okamumu/gospn/pkg/npzout"
	"github.com/okamumu/gospn/pkg/parser"
	"github.com/okamumu/gospn/pkg/petrinet"
	"github.com/okamumu/gospn/pkg/result"
)

// -update rewrites the golden files instead of comparing against them. The other
// goldens in this directory are hashes pasted from a log line; a text golden is worth
// diffing, so it is a file and it is regenerated by a flag.
var update = flag.Bool("update", false, "rewrite the golden output files")

// The nets whose marking-graph output is pinned. Small ones: the point is that the
// document is readable in a diff, not that it is large.
var goldenNets = []struct{ name, file string }{
	{"spnp_example1", "../example/spnp_example1.spn"},
	{"spnp_example2", "../example/spnp_example2.spn"},
	{"spnp_example3", "../example/spnp_example3.spn"},
}

func markResult(t *testing.T, file string) *result.Result {
	t.Helper()
	net, imark, err := parser.PNreadFromFile(file)
	if err != nil {
		t.Fatalf("%s: %v", file, err)
	}
	mg, err := petrinet.CreateMarkingGraphWithDFS(net, imark)
	if err != nil {
		t.Fatalf("%s: %v", file, err)
	}
	return analysis.MarkResult(mg)
}

// TestMarkResultJSONGolden is the first test over what a subcommand actually writes.
// The .mat and .npz say nothing to `git diff`, which is how a variable-name collision
// in the simulation output survived several releases; this one shows the names.
func TestMarkResultJSONGolden(t *testing.T) {
	for _, gn := range goldenNets {
		gn := gn
		t.Run(gn.name, func(t *testing.T) {
			var buf bytes.Buffer
			if err := jsonout.Write(&buf, markResult(t, gn.file)); err != nil {
				t.Fatal(err)
			}
			path := filepath.Join("data", "golden", gn.name+".mark.json")
			if *update {
				if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, buf.Bytes(), 0644); err != nil {
					t.Fatal(err)
				}
				t.Logf("wrote %s", path)
				return
			}
			want, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("%v (run `go test ./test -update` to create it)", err)
			}
			if !bytes.Equal(want, buf.Bytes()) {
				t.Errorf("%s differs from the golden; rerun with -update to see the diff in git", path)
			}
		})
	}
}

// TestMarkResultIsReproducible covers what -update would otherwise hide: a document
// that is written differently every run is not a golden, it is a coin toss. Two
// sources of this were fixed in TransMatrix, both of them map iteration order.
func TestMarkResultIsReproducible(t *testing.T) {
	for _, gn := range goldenNets {
		var first []byte
		for i := 0; i < 5; i++ {
			var buf bytes.Buffer
			if err := jsonout.Write(&buf, markResult(t, gn.file)); err != nil {
				t.Fatal(err)
			}
			if i == 0 {
				first = append([]byte(nil), buf.Bytes()...)
			} else if !bytes.Equal(first, buf.Bytes()) {
				t.Fatalf("%s: run %d differs from run 0", gn.name, i)
			}
		}
	}
}

// TestFormatsAgree writes one result in all three formats and reads each back. Until
// now this was checked by hand, in scipy and NPZ.jl, in a scratch directory: the check
// did not survive the session it was made in.
func TestFormatsAgree(t *testing.T) {
	cases := map[string]*result.Result{"synthetic": syntheticResult()}
	for _, gn := range goldenNets {
		cases[gn.name] = markResult(t, gn.file)
	}
	for name, res := range cases {
		name, res := name, res
		t.Run(name, func(t *testing.T) {
			checkJSON(t, res)
			checkNPZ(t, res)
			checkMAT(t, res)
		})
	}
}

// syntheticResult covers what a marking graph does not produce: integer vectors and a
// text element. `gospn sim` writes both.
func syntheticResult() *result.Result {
	res := &result.Result{}
	res.AddSparse("Q", []int32{3, 3}, 4, []int{0, 1, 2, 0}, []int{0, 2, 3, 4},
		[]float64{-1.5, 0.5, -2.25, 1e-300})
	res.AddDense("initQ", []float64{1, 0, 0})
	res.AddDense("seed", []int64{1234})
	res.AddDense("simulations", []int32{50})
	res.AddText("net", "example/mm1.spn")
	return res
}

// -- JSON ------------------------------------------------------------------

type jsonDoc struct {
	Format   string `json:"format"`
	Version  int    `json:"version"`
	Elements []struct {
		Name   string    `json:"name"`
		Kind   string    `json:"kind"`
		Dims   []int32   `json:"dims"`
		NNZ    int       `json:"nnz"`
		RowInd []int     `json:"rowind"`
		ColPtr []int     `json:"colptr"`
		Values []float64 `json:"values"`
		Text   string    `json:"text"`
	} `json:"elements"`
}

func checkJSON(t *testing.T, res *result.Result) {
	t.Helper()
	var buf bytes.Buffer
	if err := jsonout.Write(&buf, res); err != nil {
		t.Fatal(err)
	}
	var doc jsonDoc
	if err := json.Unmarshal(buf.Bytes(), &doc); err != nil {
		t.Fatal(err)
	}
	if doc.Format != "gospn-result" || doc.Version != jsonout.FormatVersion {
		t.Errorf("json: header is %q/%d", doc.Format, doc.Version)
	}
	if len(doc.Elements) != len(res.Elements) {
		t.Fatalf("json: %d elements, want %d", len(doc.Elements), len(res.Elements))
	}
	for i, got := range doc.Elements {
		want := res.Elements[i]
		if got.Name != want.Name {
			t.Errorf("json: element %d is %q, want %q", i, got.Name, want.Name)
			continue
		}
		switch want.Kind {
		case result.KindText:
			if got.Text != want.Text {
				t.Errorf("json %s: text %q, want %q", want.Name, got.Text, want.Text)
			}
		case result.KindSparse:
			if got.NNZ != want.NNZ || !equalInts(got.RowInd, want.Ir) || !equalInts(got.ColPtr, want.Jc) {
				t.Errorf("json %s: sparse structure differs", want.Name)
			}
			fallthrough
		default:
			if !equalFloats(got.Values, asFloats(t, want.Values)) {
				t.Errorf("json %s: values differ", want.Name)
			}
			if !equalInt32s(got.Dims, want.Dims) {
				t.Errorf("json %s: dims %v, want %v", want.Name, got.Dims, want.Dims)
			}
		}
	}
}

// -- NPZ -------------------------------------------------------------------

func checkNPZ(t *testing.T, res *result.Result) {
	t.Helper()
	var buf bytes.Buffer
	if err := npzout.Write(&buf, res); err != nil {
		t.Fatal(err)
	}
	z, err := zip.NewReader(bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range res.Elements {
		switch want.Kind {
		case result.KindText:
			// A string is a uint8 array of its UTF-8 bytes, not NumPy's '<U':
			// NPZ.jl fails the whole archive on the latter.
			descr, data := npyMember(t, z, want.Name)
			if descr != "|u1" {
				t.Errorf("npz %s: dtype %q, want |u1", want.Name, descr)
			}
			if string(data) != want.Text {
				t.Errorf("npz %s: text %q, want %q", want.Name, data, want.Text)
			}
		case result.KindDense:
			// A dense element keeps its Go type: an int vector is stored as <i4/<i8,
			// not widened to float64, so the reader has to look at the dtype.
			descr, data := npyMember(t, z, want.Name)
			var got []float64
			if strings.HasPrefix(descr, "<i") {
				got = asFloats(t, npyInts(t, z, want.Name))
			} else {
				got = npyValues(data)
			}
			if !equalFloats(got, asFloats(t, want.Values)) {
				t.Errorf("npz %s: values differ", want.Name)
			}
		case result.KindSparse:
			_, data := npyMember(t, z, want.Name+".data")
			if !equalFloats(npyValues(data), asFloats(t, want.Values)) {
				t.Errorf("npz %s: values differ", want.Name)
			}
			if got := npyInts(t, z, want.Name+".indices"); !equalInts(got, want.Ir) {
				t.Errorf("npz %s: indices differ", want.Name)
			}
			if got := npyInts(t, z, want.Name+".indptr"); !equalInts(got, want.Jc) {
				t.Errorf("npz %s: indptr differ", want.Name)
			}
			shape := npyInts(t, z, want.Name+".shape")
			if len(shape) != 2 || int32(shape[0]) != want.Dims[0] || int32(shape[1]) != want.Dims[1] {
				t.Errorf("npz %s: shape %v, want %v", want.Name, shape, want.Dims)
			}
		}
	}
}

// npyMember returns the dtype and the raw data of one .npy member, checking the parts
// of the format NumPy's mmap path is strict about.
func npyMember(t *testing.T, z *zip.Reader, name string) (string, []byte) {
	t.Helper()
	for _, f := range z.File {
		if f.Name != name+".npy" {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			t.Fatal(err)
		}
		defer rc.Close()
		b, err := io.ReadAll(rc)
		if err != nil {
			t.Fatal(err)
		}
		if string(b[:8]) != "\x93NUMPY\x01\x00" {
			t.Fatalf("%s: bad magic %q", name, b[:8])
		}
		n := int(binary.LittleEndian.Uint16(b[8:10]))
		if (10+n)%64 != 0 {
			t.Errorf("%s: preamble is %d bytes, not a multiple of 64", name, 10+n)
		}
		hdr := string(b[10 : 10+n])
		if !strings.HasSuffix(hdr, "\n") {
			t.Errorf("%s: header does not end with a newline", name)
		}
		return descrOf(t, name, hdr), b[10+n:]
	}
	t.Fatalf("npz: member %q not found", name)
	return "", nil
}

func descrOf(t *testing.T, name, hdr string) string {
	t.Helper()
	const key = "'descr': '"
	i := strings.Index(hdr, key)
	if i < 0 {
		t.Fatalf("%s: no descr in %q", name, hdr)
	}
	rest := hdr[i+len(key):]
	j := strings.Index(rest, "'")
	if j < 0 {
		t.Fatalf("%s: unterminated descr in %q", name, hdr)
	}
	return rest[:j]
}

func npyValues(data []byte) []float64 {
	out := make([]float64, 0, len(data)/8)
	for i := 0; i+8 <= len(data); i += 8 {
		out = append(out, math.Float64frombits(binary.LittleEndian.Uint64(data[i:i+8])))
	}
	return out
}

func npyInts(t *testing.T, z *zip.Reader, name string) []int {
	t.Helper()
	descr, data := npyMember(t, z, name)
	width, err := strconv.Atoi(strings.TrimPrefix(descr, "<i"))
	if err != nil {
		t.Fatalf("%s: dtype %q is not an integer", name, descr)
	}
	out := make([]int, 0, len(data)/width)
	for i := 0; i+width <= len(data); i += width {
		switch width {
		case 4:
			out = append(out, int(int32(binary.LittleEndian.Uint32(data[i:i+4]))))
		case 8:
			out = append(out, int(int64(binary.LittleEndian.Uint64(data[i:i+8]))))
		default:
			t.Fatalf("%s: unhandled width %d", name, width)
		}
	}
	return out
}

// -- MAT -------------------------------------------------------------------

// checkMAT does not reimplement a MATLAB v5 reader. What can be checked without one is
// that every element name is in the file and that the bytes are stable, which is what
// the format is for here: it is the one format with an existing, unchanged writer.
func checkMAT(t *testing.T, res *result.Result) {
	t.Helper()
	var a, b bytes.Buffer
	if err := matout.WriteResult(&a, res); err != nil {
		t.Fatal(err)
	}
	if err := matout.WriteResult(&b, res); err != nil {
		t.Fatal(err)
	}
	// The first 128 bytes are the header, which records the time the file was written.
	if !bytes.Equal(a.Bytes()[128:], b.Bytes()[128:]) {
		t.Error("mat: two writes of the same result differ")
	}
	for _, e := range res.Elements {
		if !bytes.Contains(a.Bytes(), []byte(e.Name)) {
			t.Errorf("mat: element %q is not in the file", e.Name)
		}
	}
}

// -- helpers ---------------------------------------------------------------

func asFloats(t *testing.T, values interface{}) []float64 {
	t.Helper()
	switch v := values.(type) {
	case []float64:
		return v
	case []int32:
		out := make([]float64, len(v))
		for i, x := range v {
			out[i] = float64(x)
		}
		return out
	case []int:
		out := make([]float64, len(v))
		for i, x := range v {
			out[i] = float64(x)
		}
		return out
	case []int64:
		out := make([]float64, len(v))
		for i, x := range v {
			out[i] = float64(x)
		}
		return out
	default:
		t.Fatalf("unhandled value type %T", values)
		return nil
	}
}

func equalFloats(a, b []float64) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		// Exact: these went through a writer and a reader, not through arithmetic.
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func equalInts(a, b []int) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func equalInt32s(a, b []int32) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
